[project]
name = "sust6003-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ffmpeg>=1.4",
    "gymnasium[mujoco]>=1.2.3",
    "kaleido>=1.2.0",
    "marimo>=0.20.2",
    "matplotlib>=3.10.8",
    "neat-python>=2.0.0",
    "networkx>=3.6.1",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
    "pygame>=2.6.1",
    "scipy>=1.17.1",
    "visualize>=0.5.1",
]
