# https://neat-python.readthedocs.io/en/latest/config_file.html


[NEAT]

# This defines how fitness is evaluated. The options are max, min, and mean.
fitness_criterion        = max

# If any genome reaches this fitness, training stops.
fitness_threshold        = 500

# This is the number of genomes per generation. Simple, medium, and complex problems require roughly 50-100, 150-300, or 500+ genomes, respectively.
pop_size                 = 150

# If this is true, the population will be restarted randomly if it dies out.
reset_on_extinction      = False

# If this is true, NEAT will continue even when the fitness threshold is reached.
no_fitness_termination   = False


[DefaultGenome]

# Determines whether a genome is allowed to make more than one mutation per generation. If true, it will only be allowed to make one mutation per generation. If false, it can make as many mutations as it wants.
single_structural_mutation   = false

# Controls whether NEAT re-tries a mutation if it fails. If true, NEAT will re-try a mutation until it succeeds. If false, NEAT will not re-try a mutation and will simply move on to the next genome.
structural_mutation_surer    = default

# Specifies how the initial bias is chosen.
bias_init_type               = gaussian

# Specifies how the initial response is chosen.
response_init_type           = gaussian

# Specifies how the initial weight is chosen.
weight_init_type             = gaussian

# Corresponds to the likelihood of disabled connections being mutated
enabled_rate_to_true_add     = 0.0

# Corresponds to the likelihood of enabled connections being mutated
enabled_rate_to_false_add    = 0.0


# Defines how many inputs the network has.
num_inputs               = 4

# Defines how many outputs the network has.
num_outputs              = 2

# Defines how many hidden NODES the INITIAL network has.
num_hidden               = 0

# Specifies the initial connected-ness of the network. Options: full, partial, full_direct. Full: all possible connections, including recurrent. Partial: some random connections. Full_direct: all possible connections are made, no recurrent.
initial_connection       = full_direct

# Specifies whether the network is feed-forward or recurrent.
feed_forward             = True


# Initial activation function for nodes.
activation_default       = tanh

# Rate at which activation functions for nodes will mutate.
activation_mutate_rate   = 0.0

# Available activation functions for nodes.
activation_options       = tanh

# Initial aggregation function for nodes.
aggregation_default      = sum

# Rate at which aggregation functions for nodes will mutate.
aggregation_mutate_rate  = 0.0

# Available aggregation functions for nodes.
aggregation_options      = sum


# Initial mean of bias.
bias_init_mean           = 0.0

# Initial standard deviation of bias.
bias_init_stdev          = 1.0

# Maximum value for bias.
bias_max_value           = 30.0

# Minimum value for bias.
bias_min_value           = -30.0

# Magnitude by which bias will change if it mutates.
bias_mutate_power        = 0.5

# Chance of bias mutating.
bias_mutate_rate         = 0.7

# Chance of bias being completely resampled.
bias_replace_rate        = 0.1


# Response controls the scaling of neuron outputs:
# output = activation(response * input)

# Initial mean of response. As it is 1, this is essentially disabled.
response_init_mean       = 1.0

# Initial standard deviation of response.
response_init_stdev      = 0.0

# Maximum value for response.
response_max_value       = 30.0

# Minimum value for response.
response_min_value       = -30.0

# Magnitude by which response will change if it mutates.
response_mutate_power    = 0.0

# Chance of response mutating.
response_mutate_rate     = 0.0

# Chance of response being completely resampled.
response_replace_rate    = 0.0


# Initial mean of weight.
weight_init_mean         = 0.0

# Initial standard deviation of weight.
weight_init_stdev        = 1.0

# Maximum value for weight.
weight_max_value         = 30.0

# Minimum value for weight.
weight_min_value         = -30.0

# Magnitude by which weight will change if it mutates.
weight_mutate_power      = 0.5

# Chance of weight mutating.
weight_mutate_rate       = 0.8

# Chance of weight being completely resampled.
weight_replace_rate      = 0.1


# If true, new connections will initially be enabled/active.
enabled_default          = True

# Chance of connection changing from enabled to disabled or vice versa when mutated.
enabled_mutate_rate      = 0.01


# Probability of adding a new connection.
conn_add_prob            = 0.5

# Probability of deleting a connection.
conn_delete_prob         = 0.3

# Probability of splitting a connection to add a new node/neuron.
node_add_prob            = 0.2

# Probability of removing a node/neuron. Note that when a node is removed, all connections to and from that node are also removed.
node_delete_prob         = 0.1



# Speciation:
# - Affects how genetic distance between two genomes is calculated.
# - This is what NEAT uses to decide whether two genomes belong to the same species.
# - The distance formula is: distance = (c1 * E / N) + (c2 * D / N) + (c3 * W)
# - E is the number of excess genes. These are genes that exist in one genome but not the other, and they are located beyond the end of the shorter genome.
# - D is the number of disjoint genes. These are genes that exist in one genome but not the other, and they are located between the start and end of the shorter genome.
# - W is the average weight difference of matching genes. Matching genes are genes that exist in both genomes and have the same innovation number.
# - N is the number of genes in the larger genome. This is used to normalize the distance, so that it is not biased towards larger genomes. However, if N is less than 20, it is set to 1 to avoid excessive distance for small genomes.
# - c1, c2, and c3 are the compatibility coefficients. They determine how much excess genes, disjoint genes, and weight differences contribute to the overall distance. Higher values for these coefficients will make genomes more likely to be considered different species.
# - In practice, c1 and c1 are often set equally.

compatibility_disjoint_coefficient = 1.0
compatibility_weight_coefficient   = 0.5

[DefaultSpeciesSet]

# This is the threshold for determining whether two genomes belong to the same species. If the distance between two genomes is less than this threshold, they are considered to be in the same species. If it is greater, they are considered to be in different species.
compatibility_threshold  = 3.0

# This controls the removal of species.
[DefaultStagnation]

# This specifies how the fitness of a species is defined.
species_fitness_func     = max

# If a species' fitness does not increase for this number of generations, the species is removed.
max_stagnation           = 15

# This number of best-performing species are protected from removal.
species_elitism          = 2


#This controls reproduction within species
[DefaultReproduction]

#This number of best-performing genomes are unchanged during reproduction.
elitism                  = 2

# This proportion of best-performing genomes reproduce, the rest die.
survival_threshold       = 0.2

# A species of genomes cannot shrink below this number of genomes.
min_species_size         = 1